title: "MindWellChat"
description: An online chatbot that provide mental health support to users using the RAG-based LLM
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false